version: '3'

services:

  app:
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn App.wsgi -b 0.0.0.0:8000"
    depends_on:
      - neo4jdb
    volumes:
      - ./src:/MassEnergizeApp
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
    - NEO4J_BOLT_URL=bolt://neo4j:neo4jpass@neo4jdb:7687

